@personId=5bb27b765ff68189f4fc6875
###
POST http://localhost:3001/api/persons  HTTP/1.1
content-type: application/json

{
    "name": "test person",
    "number": "555-12345"
}

###

PUT http://localhost:3001/api/persons/{{personId}}  HTTP/1.1
content-type: application/json

{
    "name": "test person",
    "number": "555-54231"
}


###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/{{personId}}

###
DELETE http://localhost:3001/api/persons/{{personId}}